<a href="https://colab.research.google.com/github/darshansaravanan16/numpy-Practice/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array([[1., 0., 0.],
                [0., 1., 2.]])
print(arr.ndim)

2


In [ ]:
arr = np.array([[1., 0., 0.],
                [0., 1., 2.]])
print(arr.shape)

(2, 3)


In [ ]:
arr = np.array([[1., 0., 0.],
                [0., 1., 2.]])
print(arr.size)

6


In [ ]:
arr = np.array([[1, 0, 0],
                [0, 1, 2]])
print(arr.dtype)

int64


In [ ]:
arr = np.array([[1., 0., 0.],
                [0., 1., 2.]])
print(arr.itemsize)

8


In [ ]:
arr = np.array([[1., 0., 0.],
                [0., 1., 2.]])
print(arr.data)

In [ ]:
a = np.arange(15).reshape(3, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
a = np.array([12,45,65,23])
b = np.arange(4)
c = a - b
c

array([12, 44, 63, 20])

In [ ]:
a = np.array([12,45,65,23])
a<50

array([ True,  True, False,  True])

In [ ]:
a = np.array([12,45,65,23])
a**2

array([ 144, 2025, 4225,  529])

In [ ]:
a = np.array([12,45,65,23])
a*2

array([ 24,  90, 130,  46])

In [ ]:
a = np.array([[1,7],
              [4,13]])
b= np.array([[1,5],
              [4,0]])
a * b

array([[ 1, 35],
       [16,  0]])

In [ ]:
a = np.array([[1,7],
              [4,13]])
b= np.array([[1,5],
              [4,0]])
a @ b

array([[29,  5],
       [56, 20]])

In [ ]:
a = np.array([[1,7],
              [4,13]])
b= np.array([[1,5],
              [4,0]])
b.dot(a)

array([[21, 72],
       [ 4, 28]])

In [ ]:
a = np.array([[90,5],
              [4,13]])
a.max(axis = 0)

array([90, 13])

In [ ]:
a = np.array([[90,5],
              [4,13]])
a.min(axis = 1)

array([5, 4])

In [ ]:
a = np.array([[90,5],
              [4,13]])
a.cumsum(axis = 1)

array([[90, 95],
       [ 4, 17]])

In [ ]:
a = np.array([[90,5],
              [4,13]])
a.cumsum(axis = 0)

array([[90,  5],
       [94, 18]])

In [ ]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
a = np.arange(16).reshape(4,4)
a[::2]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [ ]:
a = np.arange(16).reshape(4,4)
a[:,0]

array([ 0,  4,  8, 12])

In [ ]:
a = np.arange(16).reshape(4,4)
a[:,3]

array([ 3,  7, 11, 15])

In [ ]:
a = np.arange(16).reshape(4,4)
a[:,0:3]

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [ ]:
a = np.arange(16).reshape(4,4)
a[:,1:4]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [ ]:
a = np.arange(16).reshape(4,4)
a[:,::2]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14]])

In [ ]:
a = np.arange(16).reshape(4,4)
a[0:2, 0:2]

array([[0, 1],
       [4, 5]])

In [ ]:
a = np.arange(16).reshape(4,4)
a[2:, 2:]

array([[10, 11],
       [14, 15]])

In [ ]:
import numpy as np
a= np.array([1,2,3,4])
print(a -1)
print(a * 10)
print(a ** 2)
print(a /3)

[0 1 2 3]
[10 20 30 40]
[ 1  4  9 16]
[0.33333333 0.66666667 1.         1.33333333]


In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr1 * arr2

array([ 4, 10, 18])

In [ ]:
import numpy as  np
arr1  = np.array([[1,2,3,4]])
arr2 = np.array([[1],[2],[3],[4]])
arr1 * arr2

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

In [ ]:
a = np.array([[1,7],
              [4,13]])
np.sum(a)

np.int64(25)

In [ ]:
a = np.array([[1,7],
              [4,13]])
np.std(a)

np.float64(4.437059837324712)

In [ ]:
a = np.array([[1,7],
              [4,13]])
np.max(a)

np.int64(13)

In [ ]:
a = np.array([[1,7],
              [4,13]])
np.mean(a)

np.float64(6.25)

In [ ]:
a = np.array([[1,7],
              [4,13]])
np.var(a)

np.float64(19.6875)

In [ ]:
a = np.array([[1,7],
              [4,13]])
np.argmin(a)

np.int64(0)

In [ ]:
a = np.array([[1,7],
              [4,13]])
np.argmax(a)

np.int64(3)

In [ ]:
a = np.array([[1,7],
              [4,13]])
np.sum(a , axis =0)

array([ 5, 20])

In [ ]:
a = np.array([[1,7],
              [4,13]])
np.sum(a , axis =1)

array([ 8, 17])

In [ ]:
age = np.array([[56,4,56, 86,45,44,34],
                [12,56,36,16,19,18,65]])
child = age[age < 15]
child

array([ 4, 12])

In [ ]:
age = np.array([[56,4,56, 86,45,44,34],
                [12,56,36,16,19,18,65]])
teenage = age[ age<=18 ]
teenage

array([ 4, 12, 16, 18])

In [ ]:
age = np.array([[56,4,56, 86,45,44,34],
                [12,56,36,16,19,18,65]])
adult = age[age>=18]
adult

array([56, 56, 86, 45, 44, 34, 56, 36, 19, 18, 65])

In [ ]:
age = np.array([[56,4,56, 86,45,44,34],
                [12,56,36,16,19,18,65]])
even = age[age%2==0]
even

array([56,  4, 56, 86, 44, 34, 12, 56, 36, 16, 18])

In [ ]:
age = np.array([[56,4,56, 86,45,44,34],
                [12,56,36,16,19,18,65]])
odd = age[age%2!=0]
odd

array([45, 19, 65])

In [ ]:
age = np.array([[56,4,56, 86,45,44,34],
                [12,56,36,16,19,18,65]])
adults = np.where(age>=18, age,0)
adults

array([[56,  0, 56, 86, 45, 44, 34],
       [ 0, 56, 36,  0, 19, 18, 65]])

In [ ]:
import numpy as np
rng = np.random.default_rng()
print(rng.integers(1 , 7))


3


In [ ]:
import numpy as np
rng = np.random.default_rng(seed = 1)
print(rng.integers(low = 1 ,high = 101 , size = (3 , 4  )))

[[48 52 76 96]
 [ 4 15 83 95]
 [25 32 87 43]]


In [ ]:
print(np.random.uniform(low = -1 , high= 1 , size =3))

[-0.80617127  0.02892552 -0.92285544]


In [ ]:
rng = np.random.default_rng()
arr1 = np.array([1,2,3,4,5])
rng.shuffle(arr1)
arr1

array([5, 1, 4, 2, 3])

In [ ]:
rng = np.random.default_rng()
fruits = np.array(['apple', 'orange', 'pineapple','banana'])
fruit = rng.choice(fruits)
print(fruit)


orange


In [ ]:
rng = np.random.default_rng()
fruits = np.array(['apple', 'orange', 'pineapple','banana'])
fruits = rng.choice(fruits, size =(3,3))
print(fruits)


[['banana' 'orange' 'apple']
 ['orange' 'pineapple' 'apple']
 ['pineapple' 'banana' 'apple']]
